version: "3.8"

services:
  carelink-app:
    build: .
    container_name: carelink-backend
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./carelink-data:/data
    networks:
      - carelink-net

networks:
  carelink-net:
    driver: bridge
