spring:
  datasource:
    url: jdbc:h2:file:/data/carelinkdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
